# .circleci/config.yml for CircleCI 2.0
version: 2

anchors:
  docker:
    node_docker: &node_docker
      docker:
        - image: node:8.6.0
  cache:
    - yarn_cache_key: &yarn_cache_key yarn-packages-{{ checksum "yarn.lock" }}
    - restore_yarn_cache: &restore_yarn_cache
        restore_cache:
          keys:
            - *yarn_cache_key
    - save_yarn_cache: &save_yarn_cache
        save_cache:
          key: *yarn_cache_key
          paths:
            - ~/.cache/yarn

jobs:
  install:
    <<: *node_docker
    steps:
      - *restore_yarn_cache
      - run: yarn install --frozen-lockfile
      - *save_yarn_cache
  test:
    <<: *node_docker
    working_directory: ~/repo
    steps:
      - checkout
      - *restore_yarn_cache
      - run: yarn test
  build:
    <<: *node_docker
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn build
      - persist_to_workspace:
          root: ./dist
          paths:
            - '*'
  deploy:
    <<: *node_docker
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          git checkout --orphan gh-pages || git checkout gh-pages
          find ./ -not -name '.git' -delete
      - attach_workspace:
          at: '~/repo'
      - run: |
          git add .
          git commit -am "artifact from commit '$CIRCLE_SHA1' on '$CIRCLE_BRANCH'"
          git push gh-pages

workflows:
  version: 2
  test_and_build:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - build
            - test
